version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - TOKEN=<...>
      - LOG_LEVEL=INFO
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]